<<<<<<< HEAD   (9b2cf5 Update SPIR-V Headers to 1c6bb2743)
=======
name: Create a release branch from release tag
permissions:
  contents: write

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+'
      - '!v[0-9]+.[0-9]+.rc*'

jobs:
  prepare-release-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Prepare CHANGELOG for version
        run: |
          python utils/generate_changelog.py CHANGES "${{ github.ref_name }}" VERSION_CHANGELOG
      - name: Create release
        run: |
          gh release create -t "Release ${{ github.ref_name }}" -F VERSION_CHANGELOG "${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ github.token }}

>>>>>>> BRANCH (f4d48a Squashed 'third_party/SPIRV-Tools/' changes from 51892874b..)
