<<<<<<< HEAD   (cf7eca Update SPIR-V Headers to 5e3ad389e)
=======
name: Wasm Build
permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: '0'
      - name: Build web
        run: docker-compose -f source/wasm/docker-compose.yml --project-directory . up
      - name: Run tests
        run: node test/wasm/test.js
>>>>>>> BRANCH (495ec4 Squashed 'third_party/SPIRV-Tools/' changes from 51892874b..)
