<<<<<<< HEAD   (9b2cf5 Update SPIR-V Headers to 1c6bb2743)
=======
name: Wasm Build
permissions:
  contents: read

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: '0'
      - name: Build web
        run: docker-compose -f source/wasm/docker-compose.yml --project-directory . up
      - name: Run tests
        run: node test/wasm/test.js
>>>>>>> BRANCH (f4d48a Squashed 'third_party/SPIRV-Tools/' changes from 51892874b..)
