#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = clang --gcc-toolchain=$(TOOLCHAIN) -isysroot $(SYSROOT)
CXX = clang++ --gcc-toolchain=$(TOOLCHAIN) -isysroot $(SYSROOT)
AR = ar
LD = clang++ --gcc-toolchain=$(TOOLCHAIN) -isysroot $(SYSROOT)

INC = -I./../include/ -I./../ -I./../../
CFLAGS = -Wall -std=c++11 -fexceptions -pthread -DLOG_TAG=\"libEGL_CM_swiftshader\"
RESINC = 
LIBDIR = 
LIB = -llog -lgnustl_shared -lsupc++ 
LDFLAGS = -Wl,--version-script=./exports.map -Wl,--hash-style=both -Wl,-rpath-link=$(SYSROOT)/usr/lib -L$(SYSROOT)/usr/lib

INC_DEBUG_X86 = $(INC)
CFLAGS_DEBUG_X86 = $(CFLAGS) -g -m32
RESINC_DEBUG_X86 = $(RESINC)
RCFLAGS_DEBUG_X86 = $(RCFLAGS)
LIBDIR_DEBUG_X86 = $(LIBDIR)
LIB_DEBUG_X86 = $(LIB)
LDFLAGS_DEBUG_X86 = $(LDFLAGS) -m32
OBJDIR_DEBUG_X86 = obj/x86/Debug
DEP_DEBUG_X86 = 
OUT_DEBUG_X86 = ./../../../lib/Debug_x86/libEGL.so.1

INC_RELEASE_X86 = $(INC)
CFLAGS_RELEASE_X86 = $(CFLAGS) -O2 -m32 -DNDEBUG -DANGLE_DISABLE_TRACE
RESINC_RELEASE_X86 = $(RESINC)
RCFLAGS_RELEASE_X86 = $(RCFLAGS)
LIBDIR_RELEASE_X86 = $(LIBDIR)
LIB_RELEASE_X86 = $(LIB)
LDFLAGS_RELEASE_X86 = $(LDFLAGS) -s -m32
OBJDIR_RELEASE_X86 = obj/x86/Release
DEP_RELEASE_X86 = 
OUT_RELEASE_X86 = ./../../../lib/Release_x86/libEGL.so.1

INC_DEBUG_X64 = $(INC)
CFLAGS_DEBUG_X64 = $(CFLAGS) -g -m64 -fPIC
RESINC_DEBUG_X64 = $(RESINC)
RCFLAGS_DEBUG_X64 = $(RCFLAGS)
LIBDIR_DEBUG_X64 = $(LIBDIR)
LIB_DEBUG_X64 = $(LIB)
LDFLAGS_DEBUG_X64 = $(LDFLAGS) -m64
OBJDIR_DEBUG_X64 = obj/x64/Debug
DEP_DEBUG_X64 = 
OUT_DEBUG_X64 = ./../../../lib/Debug_x64/libEGL.so.1

INC_RELEASE_X64 = $(INC)
CFLAGS_RELEASE_X64 = $(CFLAGS) -march=core2 -O2 -m64 -fPIC -DNDEBUG -DANGLE_DISABLE_TRACE
RESINC_RELEASE_X64 = $(RESINC)
RCFLAGS_RELEASE_X64 = $(RCFLAGS)
LIBDIR_RELEASE_X64 = $(LIBDIR)
LIB_RELEASE_X64 = $(LIB)
LDFLAGS_RELEASE_X64 = $(LDFLAGS) -s -m64
OBJDIR_RELEASE_X64 = obj/x64/Release
DEP_RELEASE_X64 = 
OUT_RELEASE_X64 = ./../../../lib/Release_x64/libEGL.so.1

OBJ_DEBUG_X86 = $(OBJDIR_DEBUG_X86)/__/common/debug.o $(OBJDIR_DEBUG_X86)/Config.o $(OBJDIR_DEBUG_X86)/Display.o $(OBJDIR_DEBUG_X86)/Surface.o $(OBJDIR_DEBUG_X86)/libEGL.o $(OBJDIR_DEBUG_X86)/main.o

OBJ_RELEASE_X86 = $(OBJDIR_RELEASE_X86)/__/common/debug.o $(OBJDIR_RELEASE_X86)/Config.o $(OBJDIR_RELEASE_X86)/Display.o $(OBJDIR_RELEASE_X86)/Surface.o $(OBJDIR_RELEASE_X86)/libEGL.o $(OBJDIR_RELEASE_X86)/main.o

OBJ_DEBUG_X64 = $(OBJDIR_DEBUG_X64)/__/common/debug.o $(OBJDIR_DEBUG_X64)/Config.o $(OBJDIR_DEBUG_X64)/Display.o $(OBJDIR_DEBUG_X64)/Surface.o $(OBJDIR_DEBUG_X64)/libEGL.o $(OBJDIR_DEBUG_X64)/main.o

OBJ_RELEASE_X64 = $(OBJDIR_RELEASE_X64)/__/common/debug.o $(OBJDIR_RELEASE_X64)/Config.o $(OBJDIR_RELEASE_X64)/Display.o $(OBJDIR_RELEASE_X64)/Surface.o $(OBJDIR_RELEASE_X64)/libEGL.o $(OBJDIR_RELEASE_X64)/main.o

all: debug_x86 release_x86 debug_x64 release_x64

clean: clean_debug_x86 clean_release_x86 clean_debug_x64 clean_release_x64

before_debug_x86: 
	test -d ./../../../lib/Debug_x86 || mkdir -p ./../../../lib/Debug_x86
	test -d $(OBJDIR_DEBUG_X86)/__/common || mkdir -p $(OBJDIR_DEBUG_X86)/__/common
	test -d $(OBJDIR_DEBUG_X86) || mkdir -p $(OBJDIR_DEBUG_X86)

after_debug_x86: 
	ln -s -f ./libEGL.so.1 ./../../../lib/Debug_x86/libEGL.so

debug_x86: before_debug_x86 out_debug_x86 after_debug_x86

out_debug_x86: before_debug_x86 $(OBJ_DEBUG_X86) $(DEP_DEBUG_X86)
	$(LD) -shared $(LDFLAGS_DEBUG_X86) $(LIBDIR_DEBUG_X86) $(OBJ_DEBUG_X86) $(LIB_DEBUG_X86) -o $(OUT_DEBUG_X86)

$(OBJDIR_DEBUG_X86)/__/common/debug.o: ../common/debug.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c ../common/debug.cpp -o $(OBJDIR_DEBUG_X86)/__/common/debug.o

$(OBJDIR_DEBUG_X86)/Config.o: Config.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c Config.cpp -o $(OBJDIR_DEBUG_X86)/Config.o

$(OBJDIR_DEBUG_X86)/Display.o: Display.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c Display.cpp -o $(OBJDIR_DEBUG_X86)/Display.o

$(OBJDIR_DEBUG_X86)/Surface.o: Surface.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c Surface.cpp -o $(OBJDIR_DEBUG_X86)/Surface.o

$(OBJDIR_DEBUG_X86)/libEGL.o: libEGL.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c libEGL.cpp -o $(OBJDIR_DEBUG_X86)/libEGL.o

$(OBJDIR_DEBUG_X86)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG_X86) $(INC_DEBUG_X86) -c main.cpp -o $(OBJDIR_DEBUG_X86)/main.o

clean_debug_x86: 
	rm -f $(OBJ_DEBUG_X86) $(OUT_DEBUG_X86)
	rm -rf ./../../../lib/Debug_x86
	rm -rf $(OBJDIR_DEBUG_X86)/__/common
	rm -rf $(OBJDIR_DEBUG_X86)

before_release_x86: 
	test -d ./../../../lib/Release_x86 || mkdir -p ./../../../lib/Release_x86
	test -d $(OBJDIR_RELEASE_X86)/__/common || mkdir -p $(OBJDIR_RELEASE_X86)/__/common
	test -d $(OBJDIR_RELEASE_X86) || mkdir -p $(OBJDIR_RELEASE_X86)

after_release_x86: 
	ln -s -f ./libEGL.so.1 ./../../../lib/Release_x86/libEGL.so

release_x86: before_release_x86 out_release_x86 after_release_x86

out_release_x86: before_release_x86 $(OBJ_RELEASE_X86) $(DEP_RELEASE_X86)
	$(LD) -shared $(LDFLAGS_RELEASE_X86) $(LIBDIR_RELEASE_X86) $(OBJ_RELEASE_X86) $(LIB_RELEASE_X86) -o $(OUT_RELEASE_X86)

$(OBJDIR_RELEASE_X86)/__/common/debug.o: ../common/debug.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c ../common/debug.cpp -o $(OBJDIR_RELEASE_X86)/__/common/debug.o

$(OBJDIR_RELEASE_X86)/Config.o: Config.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c Config.cpp -o $(OBJDIR_RELEASE_X86)/Config.o

$(OBJDIR_RELEASE_X86)/Display.o: Display.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c Display.cpp -o $(OBJDIR_RELEASE_X86)/Display.o

$(OBJDIR_RELEASE_X86)/Surface.o: Surface.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c Surface.cpp -o $(OBJDIR_RELEASE_X86)/Surface.o

$(OBJDIR_RELEASE_X86)/libEGL.o: libEGL.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c libEGL.cpp -o $(OBJDIR_RELEASE_X86)/libEGL.o

$(OBJDIR_RELEASE_X86)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE_X86) $(INC_RELEASE_X86) -c main.cpp -o $(OBJDIR_RELEASE_X86)/main.o

clean_release_x86: 
	rm -f $(OBJ_RELEASE_X86) $(OUT_RELEASE_X86)
	rm -rf ./../../../lib/Release_x86
	rm -rf $(OBJDIR_RELEASE_X86)/__/common
	rm -rf $(OBJDIR_RELEASE_X86)

before_debug_x64: 
	test -d ./../../../lib/Debug_x64 || mkdir -p ./../../../lib/Debug_x64
	test -d $(OBJDIR_DEBUG_X64)/__/common || mkdir -p $(OBJDIR_DEBUG_X64)/__/common
	test -d $(OBJDIR_DEBUG_X64) || mkdir -p $(OBJDIR_DEBUG_X64)

after_debug_x64: 
	ln -s -f ./libEGL.so.1 ./../../../lib/Debug_x64/libEGL.so

debug_x64: before_debug_x64 out_debug_x64 after_debug_x64

out_debug_x64: before_debug_x64 $(OBJ_DEBUG_X64) $(DEP_DEBUG_X64)
	$(LD) -shared $(LDFLAGS_DEBUG_X64) $(LIBDIR_DEBUG_X64) $(OBJ_DEBUG_X64) $(LIB_DEBUG_X64) -o $(OUT_DEBUG_X64)

$(OBJDIR_DEBUG_X64)/__/common/debug.o: ../common/debug.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c ../common/debug.cpp -o $(OBJDIR_DEBUG_X64)/__/common/debug.o

$(OBJDIR_DEBUG_X64)/Config.o: Config.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c Config.cpp -o $(OBJDIR_DEBUG_X64)/Config.o

$(OBJDIR_DEBUG_X64)/Display.o: Display.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c Display.cpp -o $(OBJDIR_DEBUG_X64)/Display.o

$(OBJDIR_DEBUG_X64)/Surface.o: Surface.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c Surface.cpp -o $(OBJDIR_DEBUG_X64)/Surface.o

$(OBJDIR_DEBUG_X64)/libEGL.o: libEGL.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c libEGL.cpp -o $(OBJDIR_DEBUG_X64)/libEGL.o

$(OBJDIR_DEBUG_X64)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG_X64) $(INC_DEBUG_X64) -c main.cpp -o $(OBJDIR_DEBUG_X64)/main.o

clean_debug_x64: 
	rm -f $(OBJ_DEBUG_X64) $(OUT_DEBUG_X64)
	rm -rf ./../../../lib/Debug_x64
	rm -rf $(OBJDIR_DEBUG_X64)/__/common
	rm -rf $(OBJDIR_DEBUG_X64)

before_release_x64: 
	test -d ./../../../lib/Release_x64 || mkdir -p ./../../../lib/Release_x64
	test -d $(OBJDIR_RELEASE_X64)/__/common || mkdir -p $(OBJDIR_RELEASE_X64)/__/common
	test -d $(OBJDIR_RELEASE_X64) || mkdir -p $(OBJDIR_RELEASE_X64)

after_release_x64: 
	ln -s -f ./libEGL.so.1 ./../../../lib/Release_x64/libEGL.so

release_x64: before_release_x64 out_release_x64 after_release_x64

out_release_x64: before_release_x64 $(OBJ_RELEASE_X64) $(DEP_RELEASE_X64)
	$(LD) -shared $(LDFLAGS_RELEASE_X64) $(LIBDIR_RELEASE_X64) $(OBJ_RELEASE_X64) $(LIB_RELEASE_X64) -o $(OUT_RELEASE_X64)

$(OBJDIR_RELEASE_X64)/__/common/debug.o: ../common/debug.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c ../common/debug.cpp -o $(OBJDIR_RELEASE_X64)/__/common/debug.o

$(OBJDIR_RELEASE_X64)/Config.o: Config.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c Config.cpp -o $(OBJDIR_RELEASE_X64)/Config.o

$(OBJDIR_RELEASE_X64)/Display.o: Display.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c Display.cpp -o $(OBJDIR_RELEASE_X64)/Display.o

$(OBJDIR_RELEASE_X64)/Surface.o: Surface.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c Surface.cpp -o $(OBJDIR_RELEASE_X64)/Surface.o

$(OBJDIR_RELEASE_X64)/libEGL.o: libEGL.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c libEGL.cpp -o $(OBJDIR_RELEASE_X64)/libEGL.o

$(OBJDIR_RELEASE_X64)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE_X64) $(INC_RELEASE_X64) -c main.cpp -o $(OBJDIR_RELEASE_X64)/main.o

clean_release_x64: 
	rm -f $(OBJ_RELEASE_X64) $(OUT_RELEASE_X64)
	rm -rf ./../../../lib/Release_x64
	rm -rf $(OBJDIR_RELEASE_X64)/__/common
	rm -rf $(OBJDIR_RELEASE_X64)

.PHONY: before_debug_x86 after_debug_x86 clean_debug_x86 before_release_x86 after_release_x86 clean_release_x86 before_debug_x64 after_debug_x64 clean_debug_x64 before_release_x64 after_release_x64 clean_release_x64

